// constants/fileIcons.ts — extension / filename / folder-name to Material Icon
// Theme basename. Static data; the resolver lives in utils/fileIcons.ts and
// constants/materialIcons.ts maps each basename to its bundled SVG.

// Material's `document` glyph has more visual weight than the plain
// `file` outline — feels at home next to the colorful per-type icons
// instead of looking like an unloved placeholder.
export const GENERIC_FILE = 'document';
// Binary "data" files (tree row + building roof) — a hex-dump glyph reads as
// "raw bytes" for any binary, whatever its specific format.
export const GENERIC_BINARY = 'hex';
export const GENERIC_FOLDER = 'folder';

// Map file extension → Material icon basename. Keep this dense for the
// extensions our scanner typically yields. Anything missing falls
// through to the generic `file` icon.
export const EXT_ICON: Record<string, string> = {
  // TS/JS family
  '.ts': 'typescript',
  '.tsx': 'react_ts',
  '.mts': 'typescript',
  '.cts': 'typescript',
  '.js': 'javascript',
  '.jsx': 'react',
  '.mjs': 'javascript',
  '.cjs': 'javascript',
  // Web
  '.html': 'html',
  '.htm': 'html',
  '.xml': 'xml',
  '.css': 'css',
  '.scss': 'sass',
  '.sass': 'sass',
  '.less': 'less',
  '.styl': 'stylus',
  '.vue': 'vue',
  '.svelte': 'svelte',
  // Data / config
  '.json': 'json',
  '.json5': 'json',
  '.jsonc': 'json',
  '.yaml': 'yaml',
  '.yml': 'yaml',
  '.toml': 'settings',
  '.ini': 'settings',
  '.conf': 'settings',
  '.env': 'tune',
  // Docs
  '.md': 'markdown',
  '.markdown': 'markdown',
  '.mdx': 'mdx',
  '.txt': 'document',
  '.rst': 'document',
  '.pdf': 'pdf',
  // Languages
  '.py': 'python',
  '.pyi': 'python',
  '.pyx': 'python',
  '.rb': 'ruby',
  '.go': 'go',
  '.rs': 'rust',
  '.java': 'java',
  '.kt': 'kotlin',
  '.kts': 'kotlin',
  '.swift': 'swift',
  '.c': 'c',
  '.h': 'h',
  '.cpp': 'cpp',
  '.cc': 'cpp',
  '.hpp': 'hpp',
  '.cs': 'csharp',
  '.fs': 'fsharp',
  '.php': 'php',
  '.lua': 'lua',
  '.r': 'r',
  '.pl': 'perl',
  '.scala': 'scala',
  '.dart': 'dart',
  '.ex': 'elixir',
  '.exs': 'elixir',
  '.erl': 'erlang',
  '.clj': 'clojure',
  '.hs': 'haskell',
  '.zig': 'zig',
  '.nim': 'nim',
  // Shells / build
  '.sh': 'console',
  '.bash': 'console',
  '.zsh': 'console',
  '.fish': 'console',
  '.ps1': 'powershell',
  '.bat': 'console',
  '.cmd': 'console',
  '.makefile': 'makefile',
  '.mk': 'makefile',
  // SQL / queries
  '.sql': 'database',
  '.graphql': 'graphql',
  '.gql': 'graphql',
  // Image / media
  '.svg': 'svg',
  '.png': 'image',
  '.jpg': 'image',
  '.jpeg': 'image',
  '.gif': 'image',
  '.webp': 'image',
  '.bmp': 'image',
  '.ico': 'image',
  '.avif': 'image',
  '.tiff': 'image',
  '.psd': 'image',
  '.mp4': 'video',
  '.webm': 'video',
  '.mov': 'video',
  '.m4v': 'video',
  '.ogv': 'video',
  '.mkv': 'video',
  '.mp3': 'audio',
  '.wav': 'audio',
  '.flac': 'audio',
  '.aac': 'audio',
  '.m4a': 'audio',
  '.ogg': 'audio',
  // Fonts
  '.ttf': 'font',
  '.otf': 'font',
  '.woff': 'font',
  '.woff2': 'font',
  '.eot': 'font',
  // Archives
  '.zip': 'zip',
  '.tar': 'zip',
  '.gz': 'zip',
  '.tgz': 'zip',
  '.7z': 'zip',
  '.rar': 'zip',
  '.bz2': 'zip',
  // Binary data (hex is the fallback for anything unmatched)
  '.db': 'database',
  '.sqlite': 'database',
  '.sqlite3': 'database',
  '.wasm': 'assembly',
  '.so': 'lib',
  '.dylib': 'lib',
  '.a': 'lib',
  '.dll': 'exe',
  '.exe': 'exe',
  '.jar': 'jar',
  '.node': 'nodejs',
  // Other
  '.lock': 'lock',
  '.log': 'log',
  '.diff': 'diff',
  '.patch': 'diff',
};

// Map exact filename (lowercased) → Material icon basename. Beats the
// EXT_ICON map when both match, because filename hints carry richer
// semantics than the bare extension (package.json → npm, not json).
export const NAME_ICON: Record<string, string> = {
  'package.json': 'nodejs',
  'package-lock.json': 'nodejs',
  'yarn.lock': 'yarn',
  'pnpm-lock.yaml': 'pnpm',
  'bun.lockb': 'bun',
  'tsconfig.json': 'tsconfig',
  'tsconfig.node.json': 'tsconfig',
  'tsconfig.app.json': 'tsconfig',
  'tsconfig.build.json': 'tsconfig',
  dockerfile: 'docker',
  'docker-compose.yml': 'docker',
  'docker-compose.yaml': 'docker',
  '.dockerignore': 'docker',
  makefile: 'makefile',
  gnumakefile: 'makefile',
  '.gitignore': 'git',
  '.gitattributes': 'git',
  '.gitmodules': 'git',
  '.gitkeep': 'git',
  '.npmignore': 'npm',
  '.npmrc': 'npm',
  '.editorconfig': 'editorconfig',
  '.eslintrc': 'eslint',
  '.eslintrc.js': 'eslint',
  '.eslintrc.cjs': 'eslint',
  '.eslintrc.json': 'eslint',
  '.eslintrc.yaml': 'eslint',
  '.eslintrc.yml': 'eslint',
  'eslint.config.js': 'eslint',
  'eslint.config.mjs': 'eslint',
  'eslint.config.cjs': 'eslint',
  'eslint.config.ts': 'eslint',
  '.eslintignore': 'eslint',
  '.prettierrc': 'prettier',
  '.prettierrc.json': 'prettier',
  '.prettierrc.js': 'prettier',
  '.prettierrc.cjs': 'prettier',
  '.prettierrc.yaml': 'prettier',
  '.prettierrc.yml': 'prettier',
  'prettier.config.js': 'prettier',
  'prettier.config.cjs': 'prettier',
  '.prettierignore': 'prettier',
  'vite.config.js': 'vite',
  'vite.config.ts': 'vite',
  'vite.config.mjs': 'vite',
  'vitest.config.js': 'vitest',
  'vitest.config.ts': 'vitest',
  'vitest.config.mjs': 'vitest',
  'webpack.config.js': 'webpack',
  'rollup.config.js': 'rollup',
  'rollup.config.mjs': 'rollup',
  'rollup.config.ts': 'rollup',
  'tailwind.config.js': 'tailwindcss',
  'tailwind.config.ts': 'tailwindcss',
  'postcss.config.js': 'postcss',
  'jest.config.js': 'jest',
  'jest.config.ts': 'jest',
  'babel.config.js': 'babel',
  '.babelrc': 'babel',
  '.babelrc.json': 'babel',
  license: 'certificate',
  'license.txt': 'certificate',
  'license.md': 'certificate',
  copying: 'certificate',
  readme: 'readme',
  'readme.md': 'readme',
  'readme.txt': 'readme',
  changelog: 'changelog',
  'changelog.md': 'changelog',
  contributing: 'contributing',
  'contributing.md': 'contributing',
  'code_of_conduct.md': 'conduct',
  'pyproject.toml': 'python-misc',
  'requirements.txt': 'python-misc',
  'requirements-dev.txt': 'python-misc',
  'setup.py': 'python-misc',
  'setup.cfg': 'python-misc',
  pipfile: 'python-misc',
  'pipfile.lock': 'python-misc',
  'cargo.toml': 'rust',
  'cargo.lock': 'rust',
  'go.mod': 'go-mod',
  'go.sum': 'go-mod',
  gemfile: 'ruby',
  'gemfile.lock': 'ruby',
  rakefile: 'ruby',
  '.env.local': 'tune',
  '.env.example': 'tune',
  '.env.development': 'tune',
  '.env.production': 'tune',
  '.env.test': 'tune',
};

// Map exact folder name (lowercased) → Material folder-icon basename.
// Generic `folder` is the fallback. Material also has `-open` variants
// but for our tree we stick to the closed form (the chevron already
// conveys expanded/collapsed state).
export const FOLDER_ICON: Record<string, string> = {
  src: 'folder-src',
  app: 'folder-app',
  test: 'folder-test',
  tests: 'folder-test',
  __tests__: 'folder-test',
  spec: 'folder-test',
  specs: 'folder-test',
  e2e: 'folder-test',
  config: 'folder-config',
  '.config': 'folder-config',
  configs: 'folder-config',
  configuration: 'folder-config',
  views: 'folder-views',
  view: 'folder-views',
  pages: 'folder-views',
  panes: 'folder-views',
  layouts: 'folder-layout',
  components: 'folder-components',
  component: 'folder-components',
  utils: 'folder-utils',
  util: 'folder-utils',
  helpers: 'folder-helper',
  helper: 'folder-helper',
  lib: 'folder-lib',
  libs: 'folder-lib',
  shared: 'folder-shared',
  common: 'folder-shared',
  hooks: 'folder-hook',
  middleware: 'folder-middleware',
  models: 'folder-class',
  controllers: 'folder-controller',
  routes: 'folder-routes',
  api: 'folder-api',
  services: 'folder-server',
  server: 'folder-server',
  client: 'folder-client',
  images: 'folder-images',
  image: 'folder-images',
  img: 'folder-images',
  assets: 'folder-resource',
  public: 'folder-public',
  static: 'folder-public',
  docs: 'folder-docs',
  doc: 'folder-docs',
  documentation: 'folder-docs',
  examples: 'folder-examples',
  example: 'folder-examples',
  demo: 'folder-examples',
  demos: 'folder-examples',
  types: 'folder-typescript',
  typings: 'folder-typescript',
  styles: 'folder-css',
  css: 'folder-css',
  sass: 'folder-css',
  scripts: 'folder-scripts',
  bin: 'folder-tools',
  tools: 'folder-tools',
  scene: 'folder-animation',
  constants: 'folder-constant',
  constant: 'folder-constant',
  shell: 'folder-shared',
  store: 'folder-store',
  stores: 'folder-store',
  state: 'folder-store',
  '.github': 'folder-github',
  '.git': 'folder-git',
  node_modules: 'folder-node',
  dist: 'folder-dist',
  build: 'folder-dist',
  out: 'folder-dist',
  output: 'folder-dist',
  coverage: 'folder-coverage',
  '.vscode': 'folder-vscode',
  '.idea': 'folder-intellij',
};
