// constants/syntaxLanguages.ts — Static lookup tables mapping file
// extension / exact filename → hljs language id. Used by the file
// preview pane to drive highlight.js, and by the sitewide footer's
// "language" status line. Resolver functions live in
// utils/syntaxLanguages.ts.

/** hljs language hints by extension. Falls through to auto-detection if
 *  a file doesn't match anything here. Matches the languages bundled in
 *  highlight.js/lib/common (~37 langs). */
export const EXT_LANG: Record<string, string> = {
  '.js': 'javascript',
  '.mjs': 'javascript',
  '.cjs': 'javascript',
  '.ts': 'typescript',
  '.tsx': 'typescript',
  '.jsx': 'javascript',
  '.py': 'python',
  '.rb': 'ruby',
  '.go': 'go',
  '.rs': 'rust',
  '.java': 'java',
  '.kt': 'kotlin',
  '.swift': 'swift',
  '.c': 'c',
  '.h': 'c',
  '.cpp': 'cpp',
  '.hpp': 'cpp',
  '.cc': 'cpp',
  '.cs': 'csharp',
  '.php': 'php',
  '.sh': 'bash',
  '.bash': 'bash',
  '.zsh': 'bash',
  '.fish': 'shell',
  '.html': 'xml',
  '.htm': 'xml',
  '.xml': 'xml',
  '.css': 'css',
  '.scss': 'scss',
  '.less': 'less',
  '.json': 'json',
  '.yaml': 'yaml',
  '.yml': 'yaml',
  '.toml': 'ini',
  '.ini': 'ini',
  '.md': 'markdown',
  '.markdown': 'markdown',
  '.sql': 'sql',
  '.dockerfile': 'dockerfile',
  '.diff': 'diff',
  '.patch': 'diff',
  '.lua': 'lua',
  '.r': 'r',
  '.pl': 'perl',
  '.scala': 'scala',
};

/** Filename-only hints (no extension or special-cased). Lower-cased keys. */
export const NAME_LANG: Record<string, string> = {
  dockerfile: 'dockerfile',
  makefile: 'makefile',
  gnumakefile: 'makefile',
  '.gitignore': 'plaintext',
  '.gitattributes': 'plaintext',
  '.dockerignore': 'plaintext',
  '.npmignore': 'plaintext',
  '.editorconfig': 'ini',
  '.env': 'bash',
  license: 'plaintext',
  readme: 'markdown',
};

/** hljs language id → display label. e.g. 'csharp' → 'C#', 'bash' → 'Shell'. */
export const LANGUAGE_LABELS: Record<string, string> = {
  javascript: 'JavaScript',
  typescript: 'TypeScript',
  python: 'Python',
  ruby: 'Ruby',
  go: 'Go',
  rust: 'Rust',
  java: 'Java',
  kotlin: 'Kotlin',
  swift: 'Swift',
  c: 'C',
  cpp: 'C++',
  csharp: 'C#',
  php: 'PHP',
  bash: 'Shell',
  shell: 'Shell',
  xml: 'HTML',
  css: 'CSS',
  scss: 'SCSS',
  less: 'Less',
  json: 'JSON',
  yaml: 'YAML',
  ini: 'INI',
  markdown: 'Markdown',
  sql: 'SQL',
  dockerfile: 'Dockerfile',
  diff: 'Diff',
  lua: 'Lua',
  r: 'R',
  perl: 'Perl',
  scala: 'Scala',
  plaintext: 'Plain Text',
  makefile: 'Makefile',
};
