// state/settings/fields/buildings.ts — two stores: BUILDING_DIMENSIONS, which
// the workers reconstruct off-thread and so stands alone, and BUILDINGS, every
// main-thread visual knob. Each field states its own route.

import {
  settingSignal,
  FieldKind,
  ChangeRoute,
  type ConfigOf,
  type FieldMap,
} from '@/state/settings/schema';
import { DEFAULT_HUE_EXT_MAP } from '@/constants/buildings';
import { FadeDetail } from '@/types';

const FADE_DETAIL_OPTIONS = [
  { value: FadeDetail.Full, label: 'Full' },
  { value: FadeDetail.Silhouette, label: 'Silhouette' },
  { value: FadeDetail.Hidden, label: 'Hidden' },
];

// Normalised against the project's own range, so no absolute ceiling leaves a
// small repo thin. Width is logarithmic: file sizes span orders of magnitude.
const BUILDING_DIMENSIONS_FIELDS = {
  MIN_FLOORS: {
    route: ChangeRoute.Rebuild,
    kind: FieldKind.SliderField,
    default: 1,
    min: 1,
    max: 200,
    step: 1,
    label: 'Min floors',
    tip: 'Floors for the smallest file, the bottom of the height range.',
  },
  MAX_FLOORS: {
    route: ChangeRoute.Rebuild,
    kind: FieldKind.SliderField,
    default: 64,
    min: 1,
    max: 200,
    step: 1,
    label: 'Max floors',
    tip: 'Floors for the largest file, the top of the height range. Above ~200 the tallest buildings dwarf the city.',
  },
  FULL_HEIGHT_LINES: {
    route: ChangeRoute.Rebuild,
    kind: FieldKind.SliderField,
    default: 2000,
    min: 100,
    max: 10000,
    step: 100,
    label: 'Full height at (lines)',
    tip: 'Line count that earns a max-floors building. A repo whose largest file is smaller stays proportionally shorter, so tiny files read as a low-rise city.',
  },
  FLOOR_HEIGHT: {
    route: ChangeRoute.Rebuild,
    kind: FieldKind.SliderField,
    default: 16,
    min: 1,
    max: 50,
    step: 1,
    label: 'Floor height',
    tip: 'World units per floor. Above 50 the proportions stop reading as buildings.',
  },
  EMPTY_SLAB_FLOORS: {
    route: ChangeRoute.Rebuild,
    kind: FieldKind.SliderField,
    default: 0.05,
    min: 0.01,
    max: 1,
    step: 0.01,
    label: 'Empty file height',
    tip: 'An empty (0 byte) file has nothing to stack, so it renders as a flat slab. Height as a fraction of one floor, above zero so it still catches clicks.',
  },
  MIN_WIDTH: {
    route: ChangeRoute.Rebuild,
    kind: FieldKind.SliderField,
    default: 16,
    min: 1,
    max: 200,
    step: 1,
    label: 'Min width',
    tip: 'Footprint width for the smallest file, the bottom of the width range. Footprints are square, so depth matches width.',
  },
  MAX_WIDTH: {
    route: ChangeRoute.Rebuild,
    kind: FieldKind.SliderField,
    default: 128,
    min: 1,
    max: 200,
    step: 1,
    label: 'Max width',
    tip: 'Footprint width for the largest file, the top of the width range.',
  },
  FULL_WIDTH_KB: {
    route: ChangeRoute.Rebuild,
    kind: FieldKind.SliderField,
    default: 64,
    min: 1,
    max: 1024,
    step: 1,
    label: 'Full width at (KB)',
    tip: 'File size that earns a max-width footprint. A repo whose largest file is smaller keeps proportionally narrower footprints.',
  },
  DISTANCE_FROM_ROAD: {
    route: ChangeRoute.Rebuild,
    kind: FieldKind.Number,
    default: 8,
    min: 0,
    max: 50,
    step: 1,
    label: 'Distance from road',
    tip: "Gap between every building's wall and the street edge.",
  },
  DATA_HEIGHT_RATIO: {
    route: ChangeRoute.Rebuild,
    kind: FieldKind.SliderField,
    default: 0.7,
    min: 0.1,
    max: 2,
    step: 0.05,
    label: 'Data block height × width',
    tip: 'Binary files render as squat, windowless blocks sized by bytes. Height as a fraction of that width: below 1 they stay warehouse-like, above 1 they tower.',
  },
} satisfies FieldMap;

export const BUILDING_DIMENSIONS = settingSignal('BUILDING_DIMENSIONS', BUILDING_DIMENSIONS_FIELDS);
export type BuildingDimensionsConfig = ConfigOf<typeof BUILDING_DIMENSIONS_FIELDS>;

// Everything painted on top of the dimensions. The fade tiers route Live, since
// the fader subscribes here itself, so a tweak can't force a rebuild.
const BUILDINGS_FIELDS = {
  // ── Palette (HSL) — rebuild ──
  HALF_LIFE_DAYS: {
    route: ChangeRoute.Rebuild,
    kind: FieldKind.SliderField,
    default: 90,
    min: 1,
    max: 730,
    step: 1,
    label: 'Color half-life (days)',
    tip: 'Days untouched before a file is halfway to its stalest color.',
  },
  SATURATION_MIN: {
    route: ChangeRoute.Rebuild,
    kind: FieldKind.SliderField,
    default: 50,
    min: 0,
    max: 100,
    step: 5,
    label: 'Saturation min',
    tip: 'Saturation for the oldest, least-recently-modified files: how muted their color gets.',
  },
  SATURATION_MAX: {
    route: ChangeRoute.Rebuild,
    kind: FieldKind.SliderField,
    default: 100,
    min: 0,
    max: 100,
    step: 5,
    label: 'Saturation max',
    tip: 'Saturation for the newest files: how rich their color gets.',
  },
  LIGHTNESS_MIN: {
    route: ChangeRoute.Rebuild,
    kind: FieldKind.SliderField,
    default: 5,
    min: 0,
    max: 100,
    step: 5,
    label: 'Lightness min',
    tip: 'Lightness for stale files, giving them a dim, near-gray, rundown look.',
  },
  LIGHTNESS_MAX: {
    route: ChangeRoute.Rebuild,
    kind: FieldKind.SliderField,
    default: 40,
    min: 0,
    max: 100,
    step: 5,
    label: 'Lightness max',
    tip: 'Lightness for recently-modified files. Values much above 50 wash the color out toward white.',
  },
  HUE_EXT_MAP: {
    route: ChangeRoute.Rebuild,
    kind: FieldKind.HueMap,
    default: DEFAULT_HUE_EXT_MAP,
    label: 'Extension hues (0–359°)',
    tip: 'Hue per file extension, matched to the file icon color.',
  },

  // ── Outline — refresh ──
  OUTLINE_WIDTH: {
    route: ChangeRoute.Refresh,
    kind: FieldKind.Number,
    default: 4,
    min: 1,
    max: 10,
    step: 1,
    label: 'Linewidth',
    tip: 'Pixel thickness shared by per-building, hover, and selected outlines. Above 10 the wireframe occludes facade detail; below 1 it vanishes at typical zoom.',
  },
  OUTLINE_HOVER_COLOR: {
    route: ChangeRoute.Refresh,
    kind: FieldKind.Color,
    default: '#ffffff',
    label: 'Hover color',
    tip: 'Outline color when the cursor is over a building.',
  },
  OUTLINE_HOVER_OPACITY: {
    route: ChangeRoute.Refresh,
    kind: FieldKind.SliderField,
    default: 0.5,
    min: 0,
    max: 1,
    step: 0.05,
    label: 'Hover opacity',
  },
  OUTLINE_SELECTED_OPACITY: {
    route: ChangeRoute.Refresh,
    kind: FieldKind.SliderField,
    default: 1.0,
    min: 0,
    max: 1,
    step: 0.05,
    label: 'Selected opacity',
    tip: 'The selected outline always uses an animated rainbow color, tunable under Post-Processing.',
  },

  // ── Transition timing — live ──
  BUILDING_TRANSITION_MS: {
    route: ChangeRoute.Live,
    kind: FieldKind.Number,
    default: 500,
    min: 50,
    max: 3000,
    step: 10,
    label: 'Enter / refresh (ms)',
    tip: 'How long buildings fade in when they first appear or refresh. Above 3000ms feels sluggish, below 50ms reads as a hard cut.',
  },

  // ── Facade geometry — shader-side (*_FRAC), refresh ──
  SLAB_HEIGHT_FRAC: {
    route: ChangeRoute.Refresh,
    kind: FieldKind.SliderField,
    default: 0.05,
    min: 0,
    max: 0.4,
    step: 0.01,
    label: 'Slab thickness × floor',
    tip: 'Floor-slab strip height as a fraction of one floor. Above 0.4 the slab eats into the window band and the facade reads as banding instead of windows.',
  },
  WINDOW_WIDTH_FRAC: {
    route: ChangeRoute.Refresh,
    kind: FieldKind.SliderField,
    default: 0.5,
    min: 0,
    max: 1,
    step: 0.01,
    label: 'Window width × cell',
  },
  WINDOW_HEIGHT_FRAC: {
    route: ChangeRoute.Refresh,
    kind: FieldKind.SliderField,
    default: 0.45,
    min: 0,
    max: 1,
    step: 0.01,
    label: 'Window height × floor',
  },
  WINDOW_MARGIN_FRAC: {
    route: ChangeRoute.Refresh,
    kind: FieldKind.SliderField,
    default: 0.08,
    min: 0,
    max: 0.2,
    step: 0.005,
    label: 'Window margin × face',
    tip: 'Horizontal margin per edge of the window grid, as a fraction of face width. Above 0.2 there is only room for ~3 window columns on a typical building.',
  },
  DOOR_HEIGHT_FRAC: {
    route: ChangeRoute.Refresh,
    kind: FieldKind.SliderField,
    default: 0.75,
    min: 0,
    max: 1,
    step: 0.01,
    label: 'Door height × floor',
  },
  ROOF_BORDER_FRAC: {
    route: ChangeRoute.Refresh,
    kind: FieldKind.SliderField,
    default: 0.05,
    min: 0,
    max: 0.1,
    step: 0.005,
    label: 'Roof border × face',
    tip: 'Width of the roof border strip, as a fraction of the face. Above 0.1 it eats into the icon area at the top of the facade.',
  },

  // ── Facade geometry — JS-side (baked attributes), rebuild ──
  WINDOW_COLS_MAX: {
    route: ChangeRoute.Rebuild,
    kind: FieldKind.Number,
    default: 8,
    min: 1,
    max: 10,
    step: 1,
    label: 'Max window columns',
    tip: 'Hard cap on window columns per face. Above 10 the grid gets too dense to read at typical zoom.',
  },
  WIDTH_PER_WINDOW_COL: {
    route: ChangeRoute.Rebuild,
    kind: FieldKind.Number,
    default: 12,
    min: 1,
    max: 32,
    step: 1,
    label: 'Width per window col',
    tip: 'World-unit width allotted per window column. Above 32, small buildings end up with zero windows.',
  },
  DOOR_WIDTH_FRAC: {
    route: ChangeRoute.Rebuild,
    kind: FieldKind.SliderField,
    default: 0.2,
    min: 0,
    max: 1,
    step: 0.05,
    label: 'Door width',
    tip: "Door width as a fraction of the building's own width, so bigger buildings get proportionally wider doors.",
  },

  // ── Facade contrast (HSL lightness Δ) — refresh ──
  SLAB_LIGHTNESS_DELTA: {
    route: ChangeRoute.Refresh,
    kind: FieldKind.SliderField,
    default: -10,
    min: -100,
    max: 100,
    step: 1,
    label: 'Floor slab',
    tip: 'Lightness offset for the floor-slab strip, in HSL percentage points (negative darkens).',
  },
  DOOR_LIGHTNESS_DELTA: {
    route: ChangeRoute.Refresh,
    kind: FieldKind.SliderField,
    default: -50,
    min: -100,
    max: 100,
    step: 1,
    label: 'Door',
    tip: 'Lightness offset for the door (negative darkens).',
  },

  // ── Window lighting — refresh ──
  UNLIT_LIGHTNESS_DELTA: {
    route: ChangeRoute.Refresh,
    kind: FieldKind.SliderField,
    default: -10,
    min: -20,
    max: 20,
    step: 1,
    label: 'Unlit pane lightness Δ',
    tip: 'Lightness offset for unlit window panes, relative to the building hue.',
  },
  GAP_BASE_THRESHOLD: {
    route: ChangeRoute.Refresh,
    kind: FieldKind.SliderField,
    default: 0.25,
    min: 0,
    max: 1,
    step: 0.01,
    label: 'Gap fraction (base)',
    tip: 'Base fraction of cells with no window at all, as architectural gaps.',
  },
  GAP_AGE_BONUS: {
    route: ChangeRoute.Refresh,
    kind: FieldKind.SliderField,
    default: 0.5,
    min: 0,
    max: 1,
    step: 0.01,
    label: 'Gap fraction (age bonus)',
    tip: 'Extra empty-cell fraction for the oldest buildings, fading to 0 for the newest.',
  },
  LIT_FRESHNESS_EXPONENT: {
    route: ChangeRoute.Refresh,
    kind: FieldKind.SliderField,
    default: 2.0,
    min: 1,
    max: 4,
    step: 0.1,
    label: 'Lit-window dim curve',
    tip: '1 is linear; higher values mean only the freshest buildings glow, and beyond 4 only the newest ~6% of files visibly light up.',
  },
  DIM_GLOW_COLOR: {
    route: ChangeRoute.Refresh,
    kind: FieldKind.Color,
    default: '#806626',
    label: 'Old building glow',
    tip: 'Warm amber tint that lit windows drift toward as the file ages, by creation date rather than last-modified.',
  },
  WINDOW_EMISSION: {
    route: ChangeRoute.Refresh,
    kind: FieldKind.SliderField,
    default: 1.0,
    min: 0,
    max: 3.0,
    step: 0.05,
    label: 'Emission (bloom)',
    tip: "How brightly the newest building's lit windows glow, fading to none for the oldest. Requires Bloom enabled in Effects. 0 = no glow, 1 = moderate, 3 = full neon.",
  },

  // ── Billboards (media files) — rebuild (geometry baked at apply time) ──
  MEDIA_ENABLED: {
    route: ChangeRoute.Rebuild,
    kind: FieldKind.ToggleField,
    default: true,
    label: 'Enabled',
    tip: 'Render the image/video billboard on media-file buildings. Off skips the mesh entirely, no fetch or decode: the buildings still show, without the picture.',
  },
  MEDIA_SIDE_MARGIN_FRAC: {
    route: ChangeRoute.Rebuild,
    kind: FieldKind.SliderField,
    default: 0.1,
    min: 0,
    max: 0.4,
    step: 0.01,
    label: 'Side margin × width',
    tip: 'Horizontal margin on each side of the billboard, as a fraction of building width. Above 0.4 the billboard shrinks to a sliver.',
  },
  MEDIA_BOTTOM_OFFSET_FLOORS: {
    route: ChangeRoute.Rebuild,
    kind: FieldKind.SliderField,
    default: 1.0,
    min: 0,
    max: 3,
    step: 0.1,
    label: 'Bottom offset × floors',
    tip: "How many floor heights above the ground the billboard's bottom edge sits. 1.0 clears the door; raise it to lift the billboard higher on the building.",
  },
  MEDIA_PLACEHOLDER_COLOR: {
    route: ChangeRoute.Rebuild,
    kind: FieldKind.Color,
    default: '#29293d',
    label: 'Placeholder color',
    tip: 'Color shown on the billboard while the texture is loading, or if the load fails.',
  },
  MEDIA_EMISSION: {
    route: ChangeRoute.Refresh,
    kind: FieldKind.SliderField,
    default: 0.6,
    min: 0,
    max: 5.0,
    step: 0.1,
    label: 'Emission (bloom)',
    tip: 'Brightness multiplier on billboard images. Requires Bloom enabled in Effects to glow. 0 = black, 1 = normal, higher = neon storefront.',
  },

  // ── Data blocks (binary files) — rebuild ──
  DATA_ENABLED: {
    route: ChangeRoute.Rebuild,
    kind: FieldKind.ToggleField,
    default: true,
    label: 'Enabled',
    tip: 'Wrap binary-file data blocks in a facade of their own bytes: a byte-pattern fingerprint, a font glyph, or an audio waveform. Off leaves them sealed and blank.',
  },
  DATA_COLOR: {
    route: ChangeRoute.Refresh,
    kind: FieldKind.Color,
    default: '#ffffff',
    label: 'Facade color',
    tip: 'Tint for the data facades: the byte-pattern fingerprint, font glyph, and audio waveform render white by default, recolor them here.',
  },
  DATA_EMISSION: {
    route: ChangeRoute.Refresh,
    kind: FieldKind.SliderField,
    default: 0.6,
    min: 0,
    max: 5.0,
    step: 0.1,
    label: 'Emission (bloom)',
    tip: 'Brightness multiplier on the data facades. Requires Bloom enabled in Effects to glow. 0 is black, 1 is normal, higher is neon.',
  },

  // ── Aging (createdAge-driven weathering) — refresh ──
  GRIME_ENABLED: {
    route: ChangeRoute.Refresh,
    kind: FieldKind.ToggleField,
    default: true,
    label: 'Enabled',
    tip: 'Vertical streaks of darker color falling from the top of each face on aged buildings. Turn off for clean facades regardless of age.',
  },
  GRIME_INTENSITY: {
    route: ChangeRoute.Refresh,
    kind: FieldKind.RangePairField,
    default: [0, 1] as [number, number],
    min: 0,
    max: 1,
    step: 0.05,
    label: 'Intensity (new → old)',
    tip: 'How dark each streak gets, from newest buildings (left) to oldest (right). 0 is invisible, 1 is strongly darkened.',
  },
  GRIME_COVERAGE: {
    route: ChangeRoute.Refresh,
    kind: FieldKind.RangePairField,
    default: [0, 0.55] as [number, number],
    min: 0,
    max: 1,
    step: 0.05,
    label: 'Coverage (new → old)',
    tip: 'Fraction of vertical bands that streak, from newest buildings (left) to oldest (right). Lower is sparser, higher is nearly every band.',
  },

  // Every other building is tiered by directory distance from the selection:
  // DEFAULT is the selection and the idle state, 4 is everything outside it.
  DEFAULT_DETAIL: {
    route: ChangeRoute.Live,
    kind: FieldKind.Select,
    default: FadeDetail.Full,
    options: FADE_DETAIL_OPTIONS,
    label: 'Detail',
    tip: 'Full = textured walls + windows + doors. Silhouette = solid-color box. Hidden = body invisible (only outline can show).',
  },
  DEFAULT_OUTLINE: {
    route: ChangeRoute.Live,
    kind: FieldKind.ToggleField,
    default: false,
    label: 'Outline',
    tip: 'Show the wireframe edge overlay.',
  },
  DEFAULT_BODY_OPACITY: {
    route: ChangeRoute.Live,
    kind: FieldKind.SliderField,
    default: 1.0,
    min: 0,
    max: 1,
    step: 0.05,
    label: 'Body opacity',
    tip: 'Opacity for the body / silhouette layer.',
  },
  DEFAULT_OUTLINE_OPACITY: {
    route: ChangeRoute.Live,
    kind: FieldKind.SliderField,
    default: 1.0,
    min: 0,
    max: 1,
    step: 0.05,
    label: 'Outline opacity',
    tip: 'Opacity for the wireframe outline layer (only visible if Outline is on).',
  },

  // Level 1 — same dir as the selection (or the dir's direct files).
  LEVEL1_DETAIL: {
    route: ChangeRoute.Live,
    kind: FieldKind.Select,
    default: FadeDetail.Full,
    options: FADE_DETAIL_OPTIONS,
    label: 'Detail',
  },
  LEVEL1_OUTLINE: {
    route: ChangeRoute.Live,
    kind: FieldKind.ToggleField,
    default: false,
    label: 'Outline',
  },
  LEVEL1_BODY_OPACITY: {
    route: ChangeRoute.Live,
    kind: FieldKind.SliderField,
    default: 1.0,
    min: 0,
    max: 1,
    step: 0.05,
    label: 'Body opacity',
  },
  LEVEL1_OUTLINE_OPACITY: {
    route: ChangeRoute.Live,
    kind: FieldKind.SliderField,
    default: 1.0,
    min: 0,
    max: 1,
    step: 0.05,
    label: 'Outline opacity',
  },

  // Level 2 — one directory deeper than the selection.
  LEVEL2_DETAIL: {
    route: ChangeRoute.Live,
    kind: FieldKind.Select,
    default: FadeDetail.Full,
    options: FADE_DETAIL_OPTIONS,
    label: 'Detail',
  },
  LEVEL2_OUTLINE: {
    route: ChangeRoute.Live,
    kind: FieldKind.ToggleField,
    default: true,
    label: 'Outline',
  },
  LEVEL2_BODY_OPACITY: {
    route: ChangeRoute.Live,
    kind: FieldKind.SliderField,
    default: 0.5,
    min: 0,
    max: 1,
    step: 0.05,
    label: 'Body opacity',
  },
  LEVEL2_OUTLINE_OPACITY: {
    route: ChangeRoute.Live,
    kind: FieldKind.SliderField,
    default: 0.5,
    min: 0,
    max: 1,
    step: 0.05,
    label: 'Outline opacity',
  },

  // Level 3 — deeper descendants (two or more directories below).
  LEVEL3_DETAIL: {
    route: ChangeRoute.Live,
    kind: FieldKind.Select,
    default: FadeDetail.Silhouette,
    options: FADE_DETAIL_OPTIONS,
    label: 'Detail',
  },
  LEVEL3_OUTLINE: {
    route: ChangeRoute.Live,
    kind: FieldKind.ToggleField,
    default: true,
    label: 'Outline',
  },
  LEVEL3_BODY_OPACITY: {
    route: ChangeRoute.Live,
    kind: FieldKind.SliderField,
    default: 0.5,
    min: 0,
    max: 1,
    step: 0.05,
    label: 'Body opacity',
  },
  LEVEL3_OUTLINE_OPACITY: {
    route: ChangeRoute.Live,
    kind: FieldKind.SliderField,
    default: 0.75,
    min: 0,
    max: 1,
    step: 0.05,
    label: 'Outline opacity',
  },

  // Level 4 — outside the selection's subtree entirely.
  LEVEL4_DETAIL: {
    route: ChangeRoute.Live,
    kind: FieldKind.Select,
    default: FadeDetail.Silhouette,
    options: FADE_DETAIL_OPTIONS,
    label: 'Detail',
  },
  LEVEL4_OUTLINE: {
    route: ChangeRoute.Live,
    kind: FieldKind.ToggleField,
    default: true,
    label: 'Outline',
  },
  LEVEL4_BODY_OPACITY: {
    route: ChangeRoute.Live,
    kind: FieldKind.SliderField,
    default: 0.25,
    min: 0,
    max: 1,
    step: 0.05,
    label: 'Body opacity',
  },
  LEVEL4_OUTLINE_OPACITY: {
    route: ChangeRoute.Live,
    kind: FieldKind.SliderField,
    default: 0.5,
    min: 0,
    max: 1,
    step: 0.05,
    label: 'Outline opacity',
  },
} satisfies FieldMap;

export const BUILDINGS = settingSignal('BUILDINGS', BUILDINGS_FIELDS);
export type BuildingsConfig = ConfigOf<typeof BUILDINGS_FIELDS>;
