// state/settings/fields/trees.ts — one tree per commit, oldest nearest the gem.
// Height follows age, width follows files changed, colour follows how many
// commits shared that day.

import {
  settingSignal,
  FieldKind,
  ChangeRoute,
  type ConfigOf,
  type FieldMap,
} from '@/state/settings/schema';

const TREES_FIELDS = {
  ENABLED: {
    route: ChangeRoute.Refresh,
    kind: FieldKind.ToggleField,
    default: true,
    label: 'Trees enabled',
    tip: 'Master toggle. When off, every tree canopy and trunk is hidden.',
  },

  CITY_CLEARANCE_PERCENT: {
    route: ChangeRoute.Rebuild,
    kind: FieldKind.SliderField,
    default: 4,
    min: 0,
    max: 50,
    step: 1,
    label: 'Distance from city (% of island)',
    tip: 'Minimum gap from any building or street, as a share of the island, so the gap suits a small repo as well as a large one.',
  },
  CITY_CLEARANCE_LIMITS: {
    route: ChangeRoute.Rebuild,
    kind: FieldKind.RangePairField,
    default: [0, 256] as [number, number],
    min: 0,
    max: 2000,
    step: 1,
    label: 'Distance limits (world units)',
    tip: 'World-unit floor and ceiling for that gap, applied after the percentage so a huge island cannot clear a huge ring.',
  },
  DENSITY_FALLOFF: {
    route: ChangeRoute.Rebuild,
    kind: FieldKind.SliderField,
    default: 1.5,
    min: 0,
    max: 50,
    step: 0.1,
    label: 'Density falloff',
    tip: 'How tightly trees cluster near the city. 0 spreads them evenly.',
  },
  EDGE_INSET_PERCENT: {
    route: ChangeRoute.Rebuild,
    kind: FieldKind.SliderField,
    default: 1,
    min: 0,
    max: 50,
    step: 1,
    label: 'Island edge inset (% of island)',
    tip: 'How far short of the island edge trees stop, as a share of the island radius.',
  },
  EDGE_INSET_LIMITS: {
    route: ChangeRoute.Rebuild,
    kind: FieldKind.RangePairField,
    default: [0, 256] as [number, number],
    min: 0,
    max: 2000,
    step: 1,
    label: 'Inset limits (world units)',
    tip: 'World-unit floor and ceiling for the inset, applied after the percentage so a huge island keeps its rim in proportion.',
  },

  COLOR_BUSY_DAY: {
    route: ChangeRoute.Refresh,
    kind: FieldKind.Color,
    default: '#001908',
    label: 'Busy-day color',
    tip: 'Color for commits made on a busy day, when many commits share the same date.',
  },
  COLOR_SOLO_DAY: {
    route: ChangeRoute.Refresh,
    kind: FieldKind.Color,
    default: '#5a370a',
    label: 'Solo-day color',
    tip: 'Color for commits made on a solo day, the only commit on that date.',
  },
  TRUNK_COLOR: {
    route: ChangeRoute.Refresh,
    kind: FieldKind.Color,
    default: '#110c08',
    label: 'Trunk color',
    tip: 'Color of every tree trunk.',
  },
  SHADING_STRENGTH: {
    route: ChangeRoute.Rebuild,
    kind: FieldKind.SliderField,
    default: 0.65,
    min: 0,
    max: 1,
    step: 0.05,
    label: 'Shading strength',
    tip: 'Shading depth on the canopy. 0 is flat, 1 is fully dark at the base.',
  },

  MIN_HEIGHT: {
    route: ChangeRoute.Rebuild,
    kind: FieldKind.SliderField,
    default: 32,
    min: 4,
    max: 400,
    step: 4,
    label: 'Min height',
    tip: 'Tree height for the newest commit, independent of building size. Older commits grow taller toward Max height.',
  },
  MAX_HEIGHT: {
    route: ChangeRoute.Rebuild,
    kind: FieldKind.SliderField,
    default: 128,
    min: 16,
    max: 800,
    step: 4,
    label: 'Max height',
    tip: 'Tree height for the oldest commit.',
  },
  HALF_LIFE_DAYS: {
    route: ChangeRoute.Rebuild,
    kind: FieldKind.SliderField,
    default: 30,
    min: 1,
    max: 3650,
    step: 5,
    label: 'Growth half-life (days)',
    tip: 'Age at which a commit tree is halfway to full height.',
  },

  TRUNK_HEIGHT_FRAC: {
    route: ChangeRoute.Rebuild,
    kind: FieldKind.SliderField,
    default: 0.35,
    min: 0.05,
    max: 1,
    step: 0.05,
    label: 'Trunk height (% of canopy)',
  },
  CANOPY_TRUNK_OVERLAP_FRAC: {
    route: ChangeRoute.Rebuild,
    kind: FieldKind.SliderField,
    default: 0.1,
    min: 0,
    max: 1,
    step: 0.05,
    label: 'Canopy-trunk overlap (% of trunk)',
    tip: 'How much of the trunk top hides inside the canopy. 0 means the canopy just touches the trunk top; 1 means it reaches the ground and hides the whole trunk.',
  },

  MIN_WIDTH: {
    route: ChangeRoute.Rebuild,
    kind: FieldKind.SliderField,
    default: 80,
    min: 2,
    max: 400,
    step: 2,
    label: 'Min canopy width',
    tip: 'Canopy diameter for commits that changed the fewest files, independent of building size.',
  },
  MAX_WIDTH: {
    route: ChangeRoute.Rebuild,
    kind: FieldKind.SliderField,
    default: 160,
    min: 4,
    max: 600,
    step: 2,
    label: 'Max canopy width',
    tip: 'Canopy diameter for commits that changed the most files.',
  },
  TRUNK_RADIUS_FRAC: {
    route: ChangeRoute.Rebuild,
    kind: FieldKind.SliderField,
    default: 0.15,
    min: 0.05,
    max: 0.5,
    step: 0.01,
    label: 'Trunk thickness (% of canopy)',
  },
  WIDTH_AGE_FLOOR: {
    route: ChangeRoute.Rebuild,
    kind: FieldKind.SliderField,
    default: 0.5,
    min: 0,
    max: 1,
    step: 0.05,
    label: 'Age shrink floor',
    tip: 'Width multiplier for the shortest, newest trees. 1 means no shrink, 0.5 half-width saplings, 0 makes width follow height. Tallest trees stay full width.',
  },

  // Two persistent meshes snap to the active tree each frame. One width for
  // both; hover and selected differ only by colour.
  OUTLINE_WIDTH: {
    route: ChangeRoute.Refresh,
    kind: FieldKind.Number,
    default: 1,
    min: 1,
    max: 10,
    step: 1,
    label: 'Linewidth',
    tip: 'Pixel thickness shared by hover and selected canopy outlines.',
  },
  OUTLINE_HOVER_COLOR: {
    route: ChangeRoute.Refresh,
    kind: FieldKind.Color,
    default: '#ffffff',
    label: 'Hover color',
    tip: 'Outline color when a tree is hovered (not selected).',
  },
  OUTLINE_HOVER_OPACITY: {
    route: ChangeRoute.Refresh,
    kind: FieldKind.SliderField,
    default: 0.5,
    min: 0,
    max: 1,
    step: 0.05,
    label: 'Hover opacity',
  },
  OUTLINE_SELECTED_OPACITY: {
    route: ChangeRoute.Refresh,
    kind: FieldKind.SliderField,
    default: 0.75,
    min: 0,
    max: 1,
    step: 0.05,
    label: 'Selected opacity',
    tip: 'The selected outline always uses an animated rainbow color, tunable under Post-Processing.',
  },
} satisfies FieldMap;

export const TREES = settingSignal('TREES', TREES_FIELDS);
export type TreesConfig = ConfigOf<typeof TREES_FIELDS>;
