/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/config": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Config */
        get: operations["config_api_config_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/file": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get File */
        get: operations["get_file_api_file_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/commit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Commit */
        get: operations["get_commit_api_commit_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/manifest/signature": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Signature */
        get: operations["signature_api_manifest_signature_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/manifest/cache": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Clear Cache */
        delete: operations["clear_cache_api_manifest_cache_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/manifest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Manifest */
        get: operations["manifest_api_manifest_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/{full_path}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Serve */
        get: operations["serve__full_path__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** BusynessThresholds */
        BusynessThresholds: {
            /** Avg */
            avg: number;
            /** Busy */
            busy: number;
        };
        /** CacheClearResponse */
        CacheClearResponse: {
            /** Deleted */
            deleted: number;
        };
        /** CloningEvent */
        CloningEvent: {
            /** Display Root */
            display_root?: string | null;
            /** Stage */
            stage?: ("receiving" | "resolving" | "counting") | null;
            /** Percent */
            percent?: number | null;
        };
        /** CommitDetailResponse */
        CommitDetailResponse: {
            /** Sha */
            sha: string;
            /** Authors */
            authors: string[];
            /** Date */
            date: string;
            /** Subject */
            subject: string;
            /** Body */
            body: string;
        };
        /** CommitEntry */
        CommitEntry: {
            /**
             * Date
             * @description YYYY-MM-DD
             */
            date: string;
            /** Files */
            files: number;
            /** Sha */
            sha: string;
            /** Authors */
            authors: string[];
            /** Subject */
            subject: string;
            /** Same Day Total */
            same_day_total: number;
        };
        /** ConfigResponse */
        ConfigResponse: {
            /** Allowlocalrepos */
            allowLocalRepos: boolean;
        };
        /** DirNode */
        DirNode: {
            /** Name */
            name: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "directory";
            /** Path */
            path: string;
            /** Fullpath */
            fullPath: string;
            /** Children */
            children: (components["schemas"]["FileNode"] | components["schemas"]["DirNode"])[];
            /** Children Count */
            children_count: number;
            /** Children File Count */
            children_file_count: number;
            /** Children Dir Count */
            children_dir_count: number;
            /** Descendants Count */
            descendants_count: number;
            /** Descendants File Count */
            descendants_file_count: number;
            /** Descendants Dir Count */
            descendants_dir_count: number;
            /** Descendants Size */
            descendants_size: number;
            /** Descendants Ext Breakdown */
            descendants_ext_breakdown: components["schemas"]["ExtBreakdownEntry"][];
        };
        /** ErrorEvent */
        ErrorEvent: {
            /** Error */
            error: string;
        };
        /** ExtBreakdownEntry */
        ExtBreakdownEntry: {
            /** Ext */
            ext: string;
            /** Count */
            count: number;
            /** Size */
            size: number;
        };
        /** FileNode */
        FileNode: {
            /** Name */
            name: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "file";
            /** Path */
            path: string;
            /** Fullpath */
            fullPath: string;
            /** Extension */
            extension: string;
            /** Size */
            size: number;
            /** Lines */
            lines: number;
            /** Binary */
            binary: boolean;
            /** Created */
            created: string;
            /** Modified */
            modified: string;
            git: components["schemas"]["GitMeta"];
            /** Media Width */
            media_width?: number | null;
            /** Media Height */
            media_height?: number | null;
        };
        /** FinalEvent */
        FinalEvent: {
            manifest: components["schemas"]["Manifest"];
        };
        /** GitMeta */
        GitMeta: {
            /**
             * Created
             * @description ISO create date or null
             */
            created?: string | null;
            /**
             * Modified
             * @description ISO modify date or null
             */
            modified?: string | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthResponse */
        HealthResponse: {
            /** Ok */
            ok: boolean;
        };
        /** Manifest */
        Manifest: {
            /** Root */
            root: string;
            /** Scanned At */
            scanned_at: string;
            /** Signature */
            signature: string;
            /** Tree Signature */
            tree_signature: string;
            tree: components["schemas"]["DirNode"];
            repo: components["schemas"]["RepoInfo"];
            /** Commits */
            commits: components["schemas"]["CommitEntry"][];
            busyness: components["schemas"]["BusynessThresholds"];
            /** Display Root */
            display_root?: string | null;
        };
        /** RepoInfo */
        RepoInfo: {
            /** Branch */
            branch?: string | null;
            /** Remote Url */
            remote_url?: string | null;
            /** Head Sha */
            head_sha?: string | null;
            /** Head Subject */
            head_subject?: string | null;
            /** Dirty */
            dirty: boolean;
        };
        /** ScanningEvent */
        ScanningEvent: {
            /** Display Root */
            display_root?: string | null;
            /** Files Scanned */
            files_scanned?: number | null;
        };
        /** SignatureResponse */
        SignatureResponse: {
            /** Root */
            root: string;
            /** Scanned At */
            scanned_at: string;
            /** Signature */
            signature: string;
        };
        /** SkeletonEvent */
        SkeletonEvent: {
            manifest: components["schemas"]["Manifest"];
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    config_api_config_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConfigResponse"];
                };
            };
        };
    };
    get_file_api_file_get: {
        parameters: {
            query: {
                /** @description Absolute path inside a scanned root */
                path: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_commit_api_commit_get: {
        parameters: {
            query: {
                sha: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CommitDetailResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    signature_api_manifest_signature_get: {
        parameters: {
            query: {
                src: string;
                branch?: string | null;
                no_cache?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SignatureResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    clear_cache_api_manifest_cache_delete: {
        parameters: {
            query: {
                src: string;
                branch?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CacheClearResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    manifest_api_manifest_get: {
        parameters: {
            query?: {
                src?: string;
                branch?: string | null;
                no_cache?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Server-Sent Events stream (`text/event-stream`). Named events and their JSON `data` payloads: `cloning` (CloningEvent), `scanning` (ScanningEvent), `skeleton` (SkeletonEvent), `final` (FinalEvent), `error` (ErrorEvent). The client closes the connection on `final`/`error`. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CloningEvent"] | components["schemas"]["ScanningEvent"] | components["schemas"]["SkeletonEvent"] | components["schemas"]["FinalEvent"] | components["schemas"]["ErrorEvent"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    serve__full_path__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                full_path: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
