// state/reactions.ts — Settings-change → scene-rebuild / material-refresh wiring.
//
// Two string-valued computed signatures drive ONE effect each:
//   REBUILD_SIGNATURE          → scheduleRebuild   (full applyManifest)
//   REFRESH_SIGNATURE → refreshMaterials  (applyTheme only)
//
// They're GENERATED from each settings field's `route` metadata
// (ChangeRoute.Rebuild | Refresh | Live) via routeSignature() — no hand-kept
// per-store key lists. A field changing only flips the signature for its own
// route, so the wrong effect never fires (route: Live fields flip neither).
// Stores not yet migrated to settingSignal are still hand-listed in the
// legacy*Sig() helpers below until they're converted.

import { computed, effect, untracked } from '@preact/signals';

import { REBUILD_STATUS, LAST_REBUILD_ERROR, LAST_UPDATED_AT } from '@/state/runtime/manifestPoll';
import { routeSignature, ChangeRoute } from '@/state/settings/schema';

// Stores NOT yet converted to schema-driven settingSignal: their rebuild vs
// refresh routing is still hand-listed below (legacy*Sig) until Streets +
// Buildings are migrated. Every converted store routes automatically from its
// per-field `route` metadata via routeSignature() — no manual entry here.
import {
  BUILDING_DIMENSIONS,
  BUILDING_PALETTE,
  AD_PANEL,
  BUILDING_OUTLINE,
  BUILDING_AGING,
  LIGHTING,
  FACADE_DETAIL,
  WINDOW_LIGHTING,
  FACADE_GEOMETRY,
} from '@/state/settings/index';

// Min-dwell for the 'rebuilding' indicator on the material-only path.
const HOT_REBUILD_MIN_DWELL_MS = 220;

interface CommitReactionsOpts {
  world: {
    getManifest(): unknown;
    applyManifest(m: unknown): Promise<void>;
    invalidateLayoutCache(): void;
  };
  applyTheme: () => void;
}

// Legacy (not-yet-schema) stores' routing, hand-listed until they're converted.
// Each returns a JSON string that changes iff one of its keys changes; the
// computeds below concatenate this with the auto-generated routeSignature().
// Split-routed legacy store FACADE_GEOMETRY contributes only the keys for the
// relevant route.
function legacyRebuildSig(): string {
  return JSON.stringify({
    buildingDimensions: BUILDING_DIMENSIONS.value,
    buildingPalette: BUILDING_PALETTE.value,
    adPanel: AD_PANEL.value,
    // FACADE_GEOMETRY JS-driven keys (bake into per-instance attributes).
    facadeGeometry: {
      windowColsMax: FACADE_GEOMETRY.value.WINDOW_COLS_MAX,
      widthPerWindowCol: FACADE_GEOMETRY.value.WIDTH_PER_WINDOW_COL,
      doorWidthFrac: FACADE_GEOMETRY.value.DOOR_WIDTH_FRAC,
    },
  });
}

function legacyRefreshSig(): string {
  return JSON.stringify({
    buildingOutline: BUILDING_OUTLINE.value,
    buildingAging: BUILDING_AGING.value,
    lighting: LIGHTING.value,
    facadeDetail: FACADE_DETAIL.value,
    windowLighting: WINDOW_LIGHTING.value,
    // FACADE_GEOMETRY shader-side *_FRAC keys.
    facadeGeometry: {
      slabHeightFrac: FACADE_GEOMETRY.value.SLAB_HEIGHT_FRAC,
      windowWidthFrac: FACADE_GEOMETRY.value.WINDOW_WIDTH_FRAC,
      windowHeightFrac: FACADE_GEOMETRY.value.WINDOW_HEIGHT_FRAC,
      windowMarginFrac: FACADE_GEOMETRY.value.WINDOW_MARGIN_FRAC,
      doorHeightFrac: FACADE_GEOMETRY.value.DOOR_HEIGHT_FRAC,
      roofBorderFrac: FACADE_GEOMETRY.value.ROOF_BORDER_FRAC,
    },
  });
}

// ── Change signatures (auto-generated by route) ────────────────────────────
// Each is a STRING that changes iff a key with the matching route changes, so
// the effect fires only for that route — no cross-firing. routeSignature()
// compiles every schema-driven (settingSignal) field with that route; the
// legacy chunk covers stores not yet on the schema.
//   REBUILD_SIGNATURE          → scheduleRebuild   (full applyManifest)
//   REFRESH_SIGNATURE → refreshMaterials  (applyTheme only)
// (route: Live fields are in neither — read per-frame / driven elsewhere.)
const REBUILD_SIGNATURE = computed(
  () => routeSignature(ChangeRoute.Rebuild) + legacyRebuildSig()
);
const REFRESH_SIGNATURE = computed(
  () => routeSignature(ChangeRoute.Refresh) + legacyRefreshSig()
);

export function attachCommitReactions({ world, applyTheme }: CommitReactionsOpts): () => void {
  // Effects fire synchronously on first call. Suppress reactions until all
  // subscriptions are wired so the initial fire doesn't trigger a rebuild.
  let armed = false;

  let hotIdleTimer: ReturnType<typeof setTimeout> | 0 = 0;

  async function scheduleRebuild() {
    if (!armed) return;
    REBUILD_STATUS.value = 'rebuilding';
    try {
      // Config changes that hit this path always invalidate the layout cache:
      // the manifest didn't change but a layout-affecting config value did,
      // so reuseLayoutFrom would skip the recompute and the change would
      // have no visible effect. Live-update polls never trigger scheduleRebuild
      // so they keep using the cache.
      world.invalidateLayoutCache();
      const manifest = world.getManifest();
      if (manifest) {
        await world.applyManifest(manifest);
      }
      REBUILD_STATUS.value = 'idle';
      LAST_REBUILD_ERROR.value = null;
    } catch (err) {
      REBUILD_STATUS.value = 'error';
      LAST_REBUILD_ERROR.value = err instanceof Error ? err.message : String(err);
    }
  }

  function refreshMaterials() {
    if (!armed) return;
    if (hotIdleTimer) clearTimeout(hotIdleTimer);
    REBUILD_STATUS.value = 'rebuilding';
    try {
      applyTheme();
    } catch (err) {
      REBUILD_STATUS.value = 'error';
      LAST_REBUILD_ERROR.value = err instanceof Error ? err.message : String(err);
      return;
    }
    // applyTheme is synchronous; hold the 'rebuilding' indicator for a
    // min-dwell so the user sees the yellow flash. Only transition if no
    // rebuild is also in flight — applyManifest owns the final state then.
    hotIdleTimer = setTimeout(() => {
      hotIdleTimer = 0;
      if (REBUILD_STATUS.value === 'rebuilding') {
        REBUILD_STATUS.value = 'idle';
        LAST_REBUILD_ERROR.value = null;
        LAST_UPDATED_AT.value = Date.now();
      }
    }, HOT_REBUILD_MIN_DWELL_MS);
  }

  // Each effect must track ONLY its signature computed. The imperative work
  // (scheduleRebuild → applyManifest, refreshMaterials → applyTheme) reads
  // OTHER signals — notably applyTheme → _refreshSidewalkTints reads
  // picker.hover / picker.selection — so it must run untracked(); otherwise the
  // effect subscribes to hover/selection after its first run and re-fires on
  // every hover (bug #4: spurious "rebuilding" on tree hover after a save).
  const unsubRebuild = effect(() => {
    void REBUILD_SIGNATURE.value; // establish tracking
    if (!armed) return;
    untracked(() => {
      void scheduleRebuild();
    });
  });

  const unsubMaterials = effect(() => {
    void REFRESH_SIGNATURE.value; // establish tracking
    if (!armed) return;
    untracked(() => refreshMaterials());
  });

  armed = true;

  return function dispose() {
    armed = false;
    if (hotIdleTimer) {
      clearTimeout(hotIdleTimer);
      hotIdleTimer = 0;
    }
    unsubRebuild();
    unsubMaterials();
  };
}
