// state/settingsReactions.ts — Settings-change → scene-rebuild / refresh wiring.
//
// Two string-valued computed signatures drive ONE effect each:
//   REBUILD_SIGNATURE → scheduleRebuild   (full applyManifest)
//   REFRESH_SIGNATURE → flagRefresh       (the 'rebuilding' status flash only)
//
// The actual material/uniform refresh for a refresh-class Save is REACTIVE:
// the controls write the settings store on Save, and each component's own
// settings effect (plus postFx's BLOOM effect) re-applies its uniforms. This
// effect's only job is the brief 'rebuilding' status flash so the user sees
// the Save register.
//
// The signatures are GENERATED entirely from each settings field's `route`
// metadata (ChangeRoute.Rebuild | Refresh | Live) via routeSignature() — no
// hand-kept per-store key lists. A field changing only flips the signature for
// its own route, so the wrong effect never fires (route: Live fields flip
// neither). Every settings store is schema-driven, so there are no legacy lists.

import { computed, effect, untracked } from '@preact/signals';

import {
  MANIFEST,
  REBUILD_STATUS,
  RebuildStatus,
  LAST_UPDATED_AT,
  markRebuilding,
  markIdle,
  markError,
} from '@/state/stores/manifest';
import { routeSignature, ChangeRoute } from '@/state/settingsSchema';
import { isEmptyManifest } from '@/utils/manifest';

// Min-dwell for the 'rebuilding' indicator on the material-only path.
const HOT_REBUILD_MIN_DWELL_MS = 220;

interface SettingsReactionsOpts {
  /** Re-pack the current mode's scene (Live: HEAD; Timeline: union + scrub), so a
   *  Save keeps the user in the mode they're in. */
  rebuildScene(): Promise<void>;
  invalidateLayoutCache(): void;
}

// ── Change signatures (auto-generated by route) ────────────────────────────
// Each is a STRING that changes iff a key with the matching route changes, so
// the effect fires only for that route — no cross-firing. routeSignature()
// compiles every schema-driven (settingSignal) field with that route.
//   REBUILD_SIGNATURE  → scheduleRebuild   (full applyManifest)
//   REFRESH_SIGNATURE  → flagRefresh       (status flash; refresh is reactive)
// (route: Live fields are in neither — read per-frame / driven elsewhere.)
const REBUILD_SIGNATURE = computed(() => routeSignature(ChangeRoute.Rebuild));
const REFRESH_SIGNATURE = computed(() => routeSignature(ChangeRoute.Refresh));

export function attachSettingsReactions({
  rebuildScene,
  invalidateLayoutCache,
}: SettingsReactionsOpts): () => void {
  // Effects fire synchronously on first call. Suppress reactions until all
  // subscriptions are wired so the initial fire doesn't trigger a rebuild.
  let armed = false;

  let hotIdleTimer: ReturnType<typeof setTimeout> | 0 = 0;

  async function scheduleRebuild() {
    if (!armed) return;
    markRebuilding();
    try {
      // Config changes that hit this path always invalidate the layout cache:
      // the manifest didn't change but a layout-affecting config value did,
      // so reuseLayoutFrom would skip the recompute and the change would
      // have no visible effect. Live-update polls never trigger scheduleRebuild
      // so they keep using the cache.
      invalidateLayoutCache();
      // peek(), not .value: track ONLY REBUILD_SIGNATURE (a tracked read would
      // double-apply with the City render effect). MANIFEST is just the
      // "project loaded?" proxy; rebuildScene picks the right-mode city.
      if (isEmptyManifest(MANIFEST.peek())) {
        markIdle(); // no world to rebuild — settle immediately
        return;
      }
      await rebuildScene();
      // Idle is owned by the trees decoration pass (markIdle), the last stage of
      // applyManifest — setting it here would stomp its Decorating state.
    } catch (err) {
      markError(err);
    }
  }

  // The refresh itself is reactive (component + postFx effects re-apply uniforms
  // when their settings stores change on Save). This only drives the brief
  // 'rebuilding' status flash so the user sees the Save register.
  function flagRefresh() {
    if (!armed) return;
    if (hotIdleTimer) clearTimeout(hotIdleTimer);
    markRebuilding();
    // Hold the 'rebuilding' indicator for a min-dwell so the user sees the
    // yellow flash. Only transition if no rebuild is also in flight —
    // applyManifest owns the final state then.
    hotIdleTimer = setTimeout(() => {
      hotIdleTimer = 0;
      if (REBUILD_STATUS.peek() === RebuildStatus.Rebuilding) {
        markIdle();
        LAST_UPDATED_AT.value = Date.now();
      }
    }, HOT_REBUILD_MIN_DWELL_MS);
  }

  // Each effect must track ONLY its signature computed, so the imperative work
  // (which writes REBUILD_STATUS) runs untracked() — otherwise the effect would
  // subscribe to whatever those signals read and re-fire spuriously.
  const unsubRebuild = effect(() => {
    void REBUILD_SIGNATURE.value; // establish tracking
    if (!armed) return;
    untracked(() => {
      void scheduleRebuild();
    });
  });

  const unsubRefresh = effect(() => {
    void REFRESH_SIGNATURE.value; // establish tracking
    if (!armed) return;
    untracked(() => flagRefresh());
  });

  armed = true;

  return function dispose() {
    armed = false;
    if (hotIdleTimer) {
      clearTimeout(hotIdleTimer);
      hotIdleTimer = 0;
    }
    unsubRebuild();
    unsubRefresh();
  };
}
