// state/settings/reactions.ts — a committed settings change → the scene
// rebuilding or refreshing. Two route-generated signatures, one effect each.
// See README.md.

import { computed, effect, untracked } from '@preact/signals';

import { RebuildStatus, type BuildReporter } from '@/state/stores/progress';
import { routeSignature, ChangeRoute } from '@/state/settings/schema';
import type { CityScene } from '@/city/types';

// Min-dwell for the 'rebuilding' indicator on the material-only path.
const HOT_REBUILD_MIN_DWELL_MS = 220;

interface SettingsReactionsOpts {
  /** The scene to re-pack. It knows what it is showing and how to rebuild it,
   *  which is why nothing here has to be told either. */
  scene: Pick<CityScene, 'manifest' | 'repack' | 'invalidateLayoutCache'>;
  /** That city's status channel, so a Save to one nobody is waiting for cannot
   *  drive the readouts describing the one they are. */
  report: BuildReporter;
}

// ── Change signatures (auto-generated by route) ────────────────────────────
// Each changes iff a field with that route changes, so neither cross-fires.
const REBUILD_SIGNATURE = computed(() => routeSignature(ChangeRoute.Rebuild));
const REFRESH_SIGNATURE = computed(() => routeSignature(ChangeRoute.Refresh));

export function attachSettingsReactions({ scene, report }: SettingsReactionsOpts): () => void {
  // Effects fire synchronously on first call. Suppress reactions until all
  // subscriptions are wired so the initial fire doesn't trigger a rebuild.
  let armed = false;

  let hotIdleTimer: ReturnType<typeof setTimeout> | 0 = 0;

  async function scheduleRebuild() {
    if (!armed) return;
    try {
      // Always invalidate: the manifest is unchanged, so reuseLayoutFrom would
      // skip the recompute and the setting would do nothing visible.
      scene.invalidateLayoutCache();
      if (!scene.manifest.peek()) {
        report.markIdle(); // nothing on it to rebuild — settle immediately
        return;
      }
      await scene.repack();
      // Idle is owned by the trees decoration pass (markIdle), the last stage of
      // applyManifest — setting it here would stomp its Decorating state.
    } catch (err) {
      report.markError(err);
    }
  }

  // The refresh itself is reactive (see README.md); this is only the brief
  // status flash so the Save visibly registers.
  function flagRefresh() {
    if (!armed) return;
    if (hotIdleTimer) clearTimeout(hotIdleTimer);
    report.markRebuilding();
    // Min-dwell so the flash is visible, and only if no real rebuild is in
    // flight: applyManifest owns the final status then.
    hotIdleTimer = setTimeout(() => {
      hotIdleTimer = 0;
      if (report.status() === RebuildStatus.Rebuilding) report.markIdle();
    }, HOT_REBUILD_MIN_DWELL_MS);
  }

  // untracked, or the effect subscribes to whatever the imperative work reads
  // and re-fires on its own writes.
  const unsubRebuild = effect(() => {
    void REBUILD_SIGNATURE.value; // establish tracking
    if (!armed) return;
    untracked(() => {
      void scheduleRebuild();
    });
  });

  const unsubRefresh = effect(() => {
    void REFRESH_SIGNATURE.value; // establish tracking
    if (!armed) return;
    untracked(() => flagRefresh());
  });

  armed = true;

  return function dispose() {
    armed = false;
    if (hotIdleTimer) {
      clearTimeout(hotIdleTimer);
      hotIdleTimer = 0;
    }
    unsubRebuild();
    unsubRefresh();
  };
}
