// state/settings/reactions.ts — a committed settings change → the scene
// rebuilding or refreshing. Two route-generated signatures, one effect each.
// See README.md.

import { computed, effect, untracked } from '@preact/signals';

import { MANIFEST } from '@/state/stores/manifest';
import {
  REBUILD_STATUS,
  RebuildStatus,
  LAST_UPDATED_AT,
  markRebuilding,
  markIdle,
  markError,
} from '@/state/stores/build';
import { routeSignature, ChangeRoute } from '@/state/settings/schema';
import { isEmptyManifest } from '@/utils/manifest';

// Min-dwell for the 'rebuilding' indicator on the material-only path.
const HOT_REBUILD_MIN_DWELL_MS = 220;

interface SettingsReactionsOpts {
  /** Re-pack the current mode's scene (Live: HEAD; Timeline: union + scrub), so a
   *  Save keeps the user in the mode they're in. */
  rebuildScene(): Promise<void>;
  invalidateLayoutCache(): void;
}

// ── Change signatures (auto-generated by route) ────────────────────────────
// Each changes iff a field with that route changes, so neither cross-fires.
const REBUILD_SIGNATURE = computed(() => routeSignature(ChangeRoute.Rebuild));
const REFRESH_SIGNATURE = computed(() => routeSignature(ChangeRoute.Refresh));

export function attachSettingsReactions({
  rebuildScene,
  invalidateLayoutCache,
}: SettingsReactionsOpts): () => void {
  // Effects fire synchronously on first call. Suppress reactions until all
  // subscriptions are wired so the initial fire doesn't trigger a rebuild.
  let armed = false;

  let hotIdleTimer: ReturnType<typeof setTimeout> | 0 = 0;

  async function scheduleRebuild() {
    if (!armed) return;
    markRebuilding();
    try {
      // Always invalidate: the manifest is unchanged, so reuseLayoutFrom would
      // skip the recompute and the setting would do nothing visible.
      invalidateLayoutCache();
      // peek, not .value: a tracked read here double-applies with City's render
      // effect. MANIFEST is only the "project loaded?" proxy.
      if (isEmptyManifest(MANIFEST.peek())) {
        markIdle(); // no world to rebuild — settle immediately
        return;
      }
      await rebuildScene();
      // Idle is owned by the trees decoration pass (markIdle), the last stage of
      // applyManifest — setting it here would stomp its Decorating state.
    } catch (err) {
      markError(err);
    }
  }

  // The refresh itself is reactive (see README.md); this is only the brief
  // status flash so the Save visibly registers.
  function flagRefresh() {
    if (!armed) return;
    if (hotIdleTimer) clearTimeout(hotIdleTimer);
    markRebuilding();
    // Min-dwell so the flash is visible, and only if no real rebuild is in
    // flight: applyManifest owns the final status then.
    hotIdleTimer = setTimeout(() => {
      hotIdleTimer = 0;
      if (REBUILD_STATUS.peek() === RebuildStatus.Rebuilding) {
        markIdle();
        LAST_UPDATED_AT.value = Date.now();
      }
    }, HOT_REBUILD_MIN_DWELL_MS);
  }

  // untracked, or the effect subscribes to whatever the imperative work reads
  // and re-fires on its own writes.
  const unsubRebuild = effect(() => {
    void REBUILD_SIGNATURE.value; // establish tracking
    if (!armed) return;
    untracked(() => {
      void scheduleRebuild();
    });
  });

  const unsubRefresh = effect(() => {
    void REFRESH_SIGNATURE.value; // establish tracking
    if (!armed) return;
    untracked(() => flagRefresh());
  });

  armed = true;

  return function dispose() {
    armed = false;
    if (hotIdleTimer) {
      clearTimeout(hotIdleTimer);
      hotIdleTimer = 0;
    }
    unsubRebuild();
    unsubRefresh();
  };
}
